version: '3'
services:
  api:
    build:
      context: ./api
    container_name: api
    ports:
      - "3000:3000"
    environment:
      - AWS_REGION=${AWS_REGION}
      - LOG_GROUP_NAME=${LOG_GROUP_NAME}
    logging:
      driver: awslogs
      options:
        awslogs-region: ${AWS_REGION}
        awslogs-group: /aws/cloudformation/${LOG_GROUP_NAME}
        awslogs-stream-prefix: api

  nginx:
    build:
      context: ./nginx
    container_name: nginx
    ports:
      - "80:80"
    depends_on:
      - api
    environment:
      - AWS_REGION=${AWS_REGION}
      - LOG_GROUP_NAME=${LOG_GROUP_NAME}
    logging:
      driver: awslogs
      options:
        awslogs-region: ${AWS_REGION}
        awslogs-group: /aws/cloudformation/${LOG_GROUP_NAME}
        awslogs-stream-prefix: nginx

networks:
  app-network:
    driver: bridge
