version: '3'
services:
  api:
    build:
      context: ./api
    container_name: api
    ports:
      - "3000:3000"
    environment:
      - AWS_REGION=${AWS_REGION}
      - LOG_GROUP_NAME=${LOG_GROUP_NAME}
      - API_PORT=${API_PORT}
      - DB_HOST=${DB_HOST}
      - DB_PASSWORD=${DB_PASSWORD}
      - DB_DATABASE=${DB_DATABASE}
      - DB_USER=${DB_USER}
    logging:
      driver: awslogs
      options:
        awslogs-region: ${AWS_REGION}
        awslogs-group: /aws/cloudformation/${LOG_GROUP_NAME}
        awslogs-stream: api

  nginx:
    build:
      context: ./nginx
    container_name: nginx
    ports:
      - "80:80"
    environment:
      - AWS_REGION=${AWS_REGION}
      - LOG_GROUP_NAME=${LOG_GROUP_NAME}
    logging:
      driver: awslogs
      options:
        awslogs-region: ${AWS_REGION}
        awslogs-group: /aws/cloudformation/${LOG_GROUP_NAME}
        awslogs-stream: nginx

networks:
  app-network:
    driver: bridge
